/*
    Cruise Critic Database System
    SQL Server Schema

    This script creates the normalized relational schema for the Cruise Critic
    database project.
*/

-- =========================
-- Core reference tables
-- =========================

CREATE TABLE SHIP
(
    SHIP_ID NUMERIC(4,0) NOT NULL,
    SHIP_NAME VARCHAR(64) NOT NULL,
    SHIP_LAUNCH_YEAR NUMERIC(4,0) NOT NULL,
    CREW_COUNT NUMERIC(4,0) NOT NULL,
    PASSENGER_CAPACITY NUMERIC(4,0) NOT NULL,
    SHORE_EXCURSIONS NUMERIC(5,0) NOT NULL,
    CONSTRAINT PK_SHIP PRIMARY KEY (SHIP_ID),
    CONSTRAINT CK_SHIP_LAUNCH_YEAR CHECK (SHIP_LAUNCH_YEAR >= 1900),
    CONSTRAINT CK_SHIP_CREW_COUNT CHECK (CREW_COUNT > 0),
    CONSTRAINT CK_SHIP_PASSENGER_CAPACITY CHECK (PASSENGER_CAPACITY > 0),
    CONSTRAINT CK_SHIP_SHORE_EXCURSIONS CHECK (SHORE_EXCURSIONS >= 0)
);

CREATE TABLE CRUISE
(
    CRUISE_ID NUMERIC(4,0) NOT NULL,
    CRUISE_NAME VARCHAR(64) NOT NULL,
    CRUISE_LENGTH NUMERIC(2,0) NOT NULL,
    SHIP_ID NUMERIC(4,0) NOT NULL,
    CONSTRAINT PK_CRUISE PRIMARY KEY (CRUISE_ID),
    CONSTRAINT FK_CRUISE_SHIP FOREIGN KEY (SHIP_ID)
        REFERENCES SHIP (SHIP_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT CK_CRUISE_LENGTH CHECK (CRUISE_LENGTH > 0)
);

CREATE TABLE CRUISE_LINE
(
    CRUISE_LINE_ID NUMERIC(4,0) NOT NULL,
    CRUISE_LINE_NAME VARCHAR(64) NOT NULL,
    CRUISE_ID NUMERIC(4,0) NOT NULL,
    CONSTRAINT PK_CRUISE_LINE PRIMARY KEY (CRUISE_LINE_ID),
    CONSTRAINT FK_CRUISE_LINE_CRUISE FOREIGN KEY (CRUISE_ID)
        REFERENCES CRUISE (CRUISE_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);

CREATE TABLE DEPARTURE_DATE
(
    DEPARTURE_DATE_ID NUMERIC(4,0) NOT NULL,
    DEPART_DATE DATE NOT NULL,
    CONSTRAINT PK_DEPARTURE_DATE PRIMARY KEY (DEPARTURE_DATE_ID)
);

CREATE TABLE CRUISE_DATE
(
    CRUISE_ID NUMERIC(4,0) NOT NULL,
    DEPARTURE_DATE_ID NUMERIC(4,0) NOT NULL,
    CONSTRAINT PK_CRUISE_DATE PRIMARY KEY (CRUISE_ID, DEPARTURE_DATE_ID),
    CONSTRAINT FK_CRUISE_DATE_CRUISE FOREIGN KEY (CRUISE_ID)
        REFERENCES CRUISE (CRUISE_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK_CRUISE_DATE_DEPARTURE_DATE FOREIGN KEY (DEPARTURE_DATE_ID)
        REFERENCES DEPARTURE_DATE (DEPARTURE_DATE_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);

-- =========================
-- Offers, deals, and pricing
-- =========================

CREATE TABLE BONUS_OFFER
(
    BONUS_OFFER_ID NUMERIC(4,0) NOT NULL,
    BONUS_OFFER_NAME VARCHAR(128) NOT NULL,
    CONSTRAINT PK_BONUS_OFFER PRIMARY KEY (BONUS_OFFER_ID)
);

CREATE TABLE CRUISE_OFFER
(
    CRUISE_ID NUMERIC(4,0) NOT NULL,
    BONUS_OFFER_ID NUMERIC(4,0) NOT NULL,
    CONSTRAINT PK_CRUISE_OFFER PRIMARY KEY (CRUISE_ID, BONUS_OFFER_ID),
    CONSTRAINT FK_CRUISE_OFFER_CRUISE FOREIGN KEY (CRUISE_ID)
        REFERENCES CRUISE (CRUISE_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK_CRUISE_OFFER_BONUS_OFFER FOREIGN KEY (BONUS_OFFER_ID)
        REFERENCES BONUS_OFFER (BONUS_OFFER_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);

CREATE TABLE DEAL
(
    DEAL_ID NUMERIC(4,0) NOT NULL,
    DEAL_DESCRIPTION VARCHAR(1000) NOT NULL,
    PARTNER_SITE VARCHAR(1000) NOT NULL,
    CRUISE_ID NUMERIC(4,0) NOT NULL,
    CONSTRAINT PK_DEAL PRIMARY KEY (DEAL_ID),
    CONSTRAINT FK_DEAL_CRUISE FOREIGN KEY (CRUISE_ID)
        REFERENCES CRUISE (CRUISE_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);

CREATE TABLE PRICE_TIER
(
    PRICE_TIER_ID NUMERIC(4,0) NOT NULL,
    PRICE_TIER_NAME VARCHAR(32) NOT NULL,
    CONSTRAINT PK_PRICE_TIER PRIMARY KEY (PRICE_TIER_ID)
);

CREATE TABLE DEAL_TIER
(
    PRICE_TIER_ID NUMERIC(4,0) NOT NULL,
    DEAL_ID NUMERIC(4,0) NOT NULL,
    PRICE NUMERIC(9,2) NOT NULL,
    CONSTRAINT PK_DEAL_TIER PRIMARY KEY (PRICE_TIER_ID, DEAL_ID),
    CONSTRAINT FK_DEAL_TIER_PRICE_TIER FOREIGN KEY (PRICE_TIER_ID)
        REFERENCES PRICE_TIER (PRICE_TIER_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK_DEAL_TIER_DEAL FOREIGN KEY (DEAL_ID)
        REFERENCES DEAL (DEAL_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT CK_DEAL_TIER_PRICE CHECK (PRICE >= 0)
);

-- =========================
-- Customers, reviews, and ratings
-- =========================

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID NUMERIC(4,0) NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UQ_CUSTOMER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE REVIEW
(
    REVIEW_ID NUMERIC(4,0) NOT NULL,
    REVIEW_DESCRIPTION VARCHAR(1000) NOT NULL,
    CRUISE_ID NUMERIC(4,0) NOT NULL,
    CUSTOMER_ID NUMERIC(4,0) NOT NULL,
    CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_REVIEW_CRUISE FOREIGN KEY (CRUISE_ID)
        REFERENCES CRUISE (CRUISE_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK_REVIEW_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (CUSTOMER_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);

CREATE TABLE REVIEW_TYPE
(
    REVIEW_TYPE_ID NUMERIC(4,0) NOT NULL,
    REVIEW_TYPE_NAME VARCHAR(64) NOT NULL,
    CONSTRAINT PK_REVIEW_TYPE PRIMARY KEY (REVIEW_TYPE_ID)
);

CREATE TABLE RATING
(
    REVIEW_ID NUMERIC(4,0) NOT NULL,
    REVIEW_TYPE_ID NUMERIC(4,0) NOT NULL,
    SCORE NUMERIC(2,1) NOT NULL,
    CONSTRAINT PK_RATING PRIMARY KEY (REVIEW_ID, REVIEW_TYPE_ID),
    CONSTRAINT FK_RATING_REVIEW FOREIGN KEY (REVIEW_ID)
        REFERENCES REVIEW (REVIEW_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK_RATING_REVIEW_TYPE FOREIGN KEY (REVIEW_TYPE_ID)
        REFERENCES REVIEW_TYPE (REVIEW_TYPE_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT CK_RATING_SCORE CHECK (SCORE BETWEEN 0 AND 5)
);

-- =========================
-- Itineraries and ports
-- =========================

CREATE TABLE ITINERARY
(
    ITINERARY_ID NUMERIC(4,0) NOT NULL,
    CRUISE_ID NUMERIC(4,0) NOT NULL,
    CONSTRAINT PK_ITINERARY PRIMARY KEY (ITINERARY_ID),
    CONSTRAINT UQ_ITINERARY_CRUISE UNIQUE (CRUISE_ID),
    CONSTRAINT FK_ITINERARY_CRUISE FOREIGN KEY (CRUISE_ID)
        REFERENCES CRUISE (CRUISE_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);

CREATE TABLE PORT
(
    PORT_ID NUMERIC(4,0) NOT NULL,
    PORT_NAME VARCHAR(64) NOT NULL,
    PORT_LOCATION VARCHAR(64) NOT NULL,
    CONSTRAINT PK_PORT PRIMARY KEY (PORT_ID)
);

CREATE TABLE ITINERARY_PORT
(
    ITINERARY_ID NUMERIC(4,0) NOT NULL,
    PORT_ID NUMERIC(4,0) NOT NULL,
    ORDERING NUMERIC(2,0) NOT NULL,
    CONSTRAINT PK_ITINERARY_PORT PRIMARY KEY (ITINERARY_ID, PORT_ID),
    CONSTRAINT FK_ITINERARY_PORT_ITINERARY FOREIGN KEY (ITINERARY_ID)
        REFERENCES ITINERARY (ITINERARY_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK_ITINERARY_PORT_PORT FOREIGN KEY (PORT_ID)
        REFERENCES PORT (PORT_ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT CK_ITINERARY_PORT_ORDERING CHECK (ORDERING > 0)
);
