/*
    Cruise Critic Database System
    Analytical Queries
*/

-- 1. Find cruises with an average rating score of at least 4.
SELECT
    C.CRUISE_NAME,
    AVG(RA.SCORE) AS AVERAGE_RATING
FROM CRUISE AS C
JOIN REVIEW AS R
    ON C.CRUISE_ID = R.CRUISE_ID
JOIN RATING AS RA
    ON R.REVIEW_ID = RA.REVIEW_ID
GROUP BY
    C.CRUISE_NAME
HAVING
    AVG(RA.SCORE) >= 4;

-- 2. Find cruises whose departure port is Toronto.
SELECT
    C.CRUISE_NAME,
    P.PORT_NAME AS DEPARTURE_PORT
FROM CRUISE AS C
JOIN ITINERARY AS I
    ON I.CRUISE_ID = C.CRUISE_ID
JOIN ITINERARY_PORT AS IP
    ON I.ITINERARY_ID = IP.ITINERARY_ID
JOIN PORT AS P
    ON P.PORT_ID = IP.PORT_ID
WHERE
    P.PORT_NAME LIKE '%Toronto%'
    AND IP.ORDERING = 1;

-- 3. Find cruises with two or more bonus offers.
SELECT
    C.CRUISE_NAME,
    COUNT(BO.BONUS_OFFER_ID) AS BONUS_OFFER_COUNT
FROM CRUISE AS C
JOIN CRUISE_OFFER AS CO
    ON CO.CRUISE_ID = C.CRUISE_ID
JOIN BONUS_OFFER AS BO
    ON BO.BONUS_OFFER_ID = CO.BONUS_OFFER_ID
GROUP BY
    C.CRUISE_NAME
HAVING
    COUNT(BO.BONUS_OFFER_ID) >= 2;

-- 4. Find cruises with ships that can hold 3000 or more passengers and leave after 2025-11-01.
SELECT
    C.CRUISE_NAME,
    S.PASSENGER_CAPACITY,
    DD.DEPART_DATE
FROM CRUISE AS C
JOIN SHIP AS S
    ON S.SHIP_ID = C.SHIP_ID
JOIN CRUISE_DATE AS CD
    ON CD.CRUISE_ID = C.CRUISE_ID
JOIN DEPARTURE_DATE AS DD
    ON DD.DEPARTURE_DATE_ID = CD.DEPARTURE_DATE_ID
WHERE
    S.PASSENGER_CAPACITY >= 3000
    AND DD.DEPART_DATE > '2025-11-01';

-- 5. Management report: price range by cruise.
SELECT
    C.CRUISE_NAME,
    MIN(DT.PRICE) AS MIN_PRICE,
    MAX(DT.PRICE) AS MAX_PRICE,
    COUNT(DISTINCT D.DEAL_ID) AS DEAL_COUNT
FROM CRUISE AS C
JOIN DEAL AS D
    ON D.CRUISE_ID = C.CRUISE_ID
JOIN DEAL_TIER AS DT
    ON DT.DEAL_ID = D.DEAL_ID
GROUP BY
    C.CRUISE_NAME
ORDER BY
    MIN_PRICE ASC;

-- 6. Management report: average rating by cruise line.
SELECT
    CL.CRUISE_LINE_NAME,
    C.CRUISE_NAME,
    AVG(RA.SCORE) AS AVERAGE_RATING
FROM CRUISE_LINE AS CL
JOIN CRUISE AS C
    ON C.CRUISE_ID = CL.CRUISE_ID
JOIN REVIEW AS R
    ON R.CRUISE_ID = C.CRUISE_ID
JOIN RATING AS RA
    ON RA.REVIEW_ID = R.REVIEW_ID
GROUP BY
    CL.CRUISE_LINE_NAME,
    C.CRUISE_NAME
ORDER BY
    AVERAGE_RATING DESC;

-- 7. Operational report: itinerary stop count by cruise.
SELECT
    C.CRUISE_NAME,
    COUNT(IP.PORT_ID) AS PORT_COUNT
FROM CRUISE AS C
JOIN ITINERARY AS I
    ON I.CRUISE_ID = C.CRUISE_ID
JOIN ITINERARY_PORT AS IP
    ON IP.ITINERARY_ID = I.ITINERARY_ID
GROUP BY
    C.CRUISE_NAME
ORDER BY
    PORT_COUNT DESC;
