/*
    Cruise Critic Database System
    Drop script for local reset.
*/

DROP TABLE IF EXISTS ITINERARY_PORT;
DROP TABLE IF EXISTS PORT;
DROP TABLE IF EXISTS ITINERARY;
DROP TABLE IF EXISTS RATING;
DROP TABLE IF EXISTS REVIEW_TYPE;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS DEAL_TIER;
DROP TABLE IF EXISTS PRICE_TIER;
DROP TABLE IF EXISTS DEAL;
DROP TABLE IF EXISTS CRUISE_OFFER;
DROP TABLE IF EXISTS BONUS_OFFER;
DROP TABLE IF EXISTS CRUISE_DATE;
DROP TABLE IF EXISTS DEPARTURE_DATE;
DROP TABLE IF EXISTS CRUISE_LINE;
DROP TABLE IF EXISTS CRUISE;
DROP TABLE IF EXISTS SHIP;
